'use strict';

/*
 * Licensed To: ThoughtExecution
 * Authored By: Rishi Raj Bansal
 * Developed in: May 2018
 *
*/

const path = require('path');
const app = require(path.join(__dirname, '../../main/app'));

const ACTION_HELLO_METHOD_HELLO                              		=	"hello";
const ACTION_LOGIN_METHOD_LOGIN_LOAD                              	=	"loadLogin";
const ACTION_LOGIN_METHOD_LOGIN_SAVE                              	=	"saveLogin";
const ACTION_LOGOUT_METHOD_LOGOUT 									=	"logout";

const ACTION_HOME_METHOD_HOME_LOAD 									=	"loadHome";
const ACTION_HOME_METHOD_HOME_SAVE 									=	"saveHome";
const ACTION_HOME_METHOD_DOWNLOAD 									=	"download";


const ACTION_LOGIN_METHOD_FORGOT_PWD_LOAD 							=	"loadForgotPassword";
const ACTION_LOGIN_METHOD_FORGOT_PWD_SAVE 							=	"saveForgotPassword";



module.exports = {
	ACTION_HELLO_METHOD_HELLO,
	ACTION_LOGIN_METHOD_LOGIN_LOAD,
	ACTION_LOGIN_METHOD_LOGIN_SAVE,
	ACTION_LOGOUT_METHOD_LOGOUT,
	ACTION_HOME_METHOD_HOME_LOAD,
	ACTION_HOME_METHOD_HOME_SAVE,
	ACTION_LOGIN_METHOD_FORGOT_PWD_LOAD,
	ACTION_LOGIN_METHOD_FORGOT_PWD_SAVE,
	ACTION_HOME_METHOD_DOWNLOAD
}

app.locals.actionMethods = [{
	ACTION_HELLO_METHOD_HELLO: ACTION_HELLO_METHOD_HELLO,
	ACTION_LOGIN_METHOD_LOGIN_LOAD: ACTION_LOGIN_METHOD_LOGIN_LOAD,
	ACTION_LOGIN_METHOD_LOGIN_SAVE: ACTION_LOGIN_METHOD_LOGIN_SAVE,
	ACTION_LOGOUT_METHOD_LOGOUT: ACTION_LOGOUT_METHOD_LOGOUT,
	ACTION_HOME_METHOD_HOME_LOAD: ACTION_HOME_METHOD_HOME_LOAD,
	ACTION_HOME_METHOD_HOME_SAVE: ACTION_HOME_METHOD_HOME_SAVE,
	ACTION_LOGIN_METHOD_FORGOT_PWD_LOAD: ACTION_LOGIN_METHOD_FORGOT_PWD_LOAD,
	ACTION_LOGIN_METHOD_FORGOT_PWD_SAVE: ACTION_LOGIN_METHOD_FORGOT_PWD_SAVE,
	ACTION_HOME_METHOD_DOWNLOAD: ACTION_HOME_METHOD_DOWNLOAD
}];